---
Gemfile:
  optional:
    ':test':
      - gem: 'fakefs'
      - gem: 'zabbixapi'
      - gem: puppet-lint-param-docs
spec/spec_helper.rb:
  mock_with: ':mocha'
  spec_overrides: "require 'support/acceptance/supported_versions'"
spec/spec_helper_acceptance.rb:
  unmanaged: false
.github/workflows/ci.yml:
  pidfile_workaround: CentOS,Ubuntu
