---
Gemfile:
  optional:
    ':test':
      - gem: 'fakefs'
      - gem: 'zabbixapi'
spec/spec_helper.rb:
  mock_with: ':mocha'
spec/spec_helper_acceptance.rb:
  unmanaged: false
.github/workflows/ci.yml:
  pidfile_workaround: CentOS,Ubuntu
